### PR TITLE
Update to v0.20.0

### LINKED ISSUE #11: Package is finally (largely) obsolete 🎉
### Comment:

Since cartopy v0.20, there's an env variable `${CARTOPY_DATA_DIR}` which cartopy directly uses for setting the path to pre-existing data. In addition, there now is a `stalled when cartopy is installed which provides feature download.

So we could boil down this package to:

1. install cartopy at build time
2. run `cartopy_feature_download.py --output ${PREFIX}/... gshhs physical cultural cultural-extra`
3. Make sure `${CARTOPY_DATA_DIR}` is set when the env activates.

Only thing missing would be the Antarctic ice shelf polygons which @xylar added.

### PR DESCRIPTION
**Pull request by xylar**
With this update, we no longer use the cartopy_offlinedata package, we just download the data using cartopy itself.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #11

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@willirath, I've put in a PR that should add the antarctic ice shelves to cartopy downloads: https://github.com/SciTools/cartopy/pull/2097

In the meantime, there's a script here to do that.

I'm downloading the cartopy source code here just so the bot will keep us in sync, though we don't really need to build a new package for every cartopy version.

**Comment by xylar** [comment]
I'm running some tests with some downstream software (https://github.com/MPAS-Dev/MPAS-Analysis) to make sure there are no surprises.

**Comment by willirath** [comment]
> I'm downloading the cartopy source code here just so the bot will keep us in sync, though we don't really need to build a new package for every cartopy version.

I agree. But closely following cartopy releases also provides immediate warning when cartopy changes anything that breaks our workflow here.

**Comment by xylar** [comment]
> But closely following cartopy releases also provides immediate warning when cartopy changes anything that breaks our workflow here.

Yep, good point.  We can always make sure CI passes for each cartopy release even if we just close the PR after that.

**Review by willirath — APPROVED** [review]
Looks good!

**Comment by willirath** [comment]
All checks passing. @xylar do you want to do more tests, or should we merge?

**Comment by xylar** [comment]
I got kicked off of the supercomputer where I was doing the testing without explanation!  I'll try again elsewhere.

**Comment by xylar** [comment]
I think my testing job is going to time out before it finishes but it would have shown a bunch of Download warnings if things weren't working.

**Pull request merged**
